### ISSUE TITLE
Does this work with Things 3

### ISSUE THREAD

**Issue by broskees** [nicolai86/things-cloud-sdk#6]
Hi there!

Couple questions:
- Do you have any plans for continuing development of this? 
- Does this function with the current state of Things?

**Comment by nicolai86** [comment]
Hey @broskees 

this project works fine for the things cloud API, which is used by things 3. 
With the current status you can read and write to the things cloud API; the usability is a pretty rough, but it works.

I'm using this myself and it works ok. Development will continue but very sporadic as I my needs change.
