### ISSUE TITLE
SLA version HTML link when registering not working anymore 

### ISSUE THREAD

**Issue by dizys** [nicolai86/things-cloud-sdk#7]
The SLA version link used to accept user agreements when registering seems not to be working anymore:

https://github.com/nicolai86/things-cloud-sdk/blob/fb45ffd7f1115c4436a6980214318d3e13328f95/account.go#L71

The response of the PUT request is: `400 Bad Request`
```json
{
    "IsSyncronyErrorResponse": true
}
```

Could you please confirm this and maybe update with a newer solution? Many many thanks!

**Comment by nicolai86** [comment]
I fixed this with the latest update - the URL of the SLA is now different.
